---
title: "Meritocracy and distributive preferences ISSP"
csl: "../input/bib/apa6.csl"
bibliography: "../input/bib/zlibrary.bib"
author: " "
output:
    html_document:
        smart: false
        includes:
          in_header: head_github-activity.html
---

## This is the project website for testing the relation about meritocratic beliefs and redistribution preferences.

Last update: `r format(Sys.time(), "%A %d %B %Y %X")`

### Authors:

- Juan Carlos Castillo, Departamento de Sociología, Universidad de Chile. [juancastillov@uchile.cl](juancastillov@uchile.cl), [jc-castillo.com](http://jc-castillo.com/)

### In brief:




### Structure of the project website:

- The tabs follow the logic of the [IPO protocol](https://github.com/juancarloscastillo/ipo) for academic workflows, based on three main components = **I**nput -> **P**roduction -> **O**utput. Here we show only one the main parts of each component: Data -> Analysis -> Paper. The complete reproducible files are in the [Github repo: https://juancarloscastillo.github.io/meritocracy-preferences/](https://juancarloscastillo.github.io/meritocracy-preferences/)

  - _Data_: pre-processing and general descriptives
  - _Analysis_: CFA (Confirmatory Factor Analysis) and measurement invariance
  - _Paper_: final output

### Reproducibility and documentation

The repository of the project in Github is structured according to the [IPO reproducibility protocol](https://juancarloscastillo.github.io/ipo/).


<br>

## [Github activity feed](https://github.com/juancarloscastillo/github-activity)


## References
